behaviors:
  PlayerBehaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 2048
      learning_rate: 3e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 64
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    max_steps: 10000000
    time_horizon: 32
    summary_freq: 10000
    threaded: true
    self_play:
      save_steps: 20000
      team_change: 100000
      swap_steps: 100000
      window: 10
      play_against_latest_model_ratio: 0.5